In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [3]:
print(a+b)  # Output: [5 7 9]

[5 7 9]


In [4]:
print(a-b)  # Output: [-3 -3 -3]

[-3 -3 -3]


In [5]:
print(a/b) # Output: [0.25 0.4  0.5 ]

[0.25 0.4  0.5 ]


In [6]:
print(a*b) # Output: [ 4 10 18 ]

[ 4 10 18]


In [7]:
print(a//b) # Output: [0 0 0 ]

[0 0 0]


In [8]:
print(b//a) # Output: [4 2 2 ]

[4 2 2]


In [9]:
print(b%a) # Output: [0 1 0 ]

[0 1 0]


In [10]:
print(a**2)

[1 4 9]
