In [2]:
import numpy as np

In [5]:
range = np.arange(1, 10, 2)

In [6]:
print(range)

[1 3 5 7 9]


In [7]:
arr = np.linspace(0, 1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [3]:
arr = np.logspace(1, 3, 3)
print(arr)

[  10.  100. 1000.]


In [4]:
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [ ]:
arr = np.zeros((2, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
arr = np.ones((3, 4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
arr = np.full(10, 2)
print(arr)

[2 2 2 2 2 2 2 2 2 2]


In [8]:
arr = np.full((2, 2), 7)
print(arr)

[[7 7]
 [7 7]]


In [13]:
arr = np.empty((2, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
arr = np.random.rand(3, 2)
print(arr)

[[0.85785688 0.10106255]
 [0.06716739 0.84810753]
 [0.37076636 0.56335836]]


In [15]:
arr = np.random.randn(4)
print(arr)

[-1.2842437   1.94459579  1.28498092 -0.88776419]


In [16]:
arr = np.random.randint(1, 10, size=(2, 3))
print(arr)

[[9 6 7]
 [5 2 3]]
