In [6]:
import numpy as np

In [7]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [8]:
print(type(arr))

<class 'numpy.ndarray'>


In [9]:
arr.dtype

dtype('int64')

In [10]:
lst = ["string", 1, 2.2, True]
arr = np.array(lst)
arr

array(['string', '1', '2.2', 'True'], dtype='<U32')

In [11]:
print(type(arr))

<class 'numpy.ndarray'>


In [12]:
arr.dtype

dtype('<U32')

In [13]:
arr = np.array([1, 2, 3, 4, 5], dtype = np.float64)
arr

array([1., 2., 3., 4., 5.])

In [14]:
arr.dtype

dtype('float64')

In [16]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [18]:
new_arr = arr.astype(np.float64)
new_arr

array([1., 2., 3., 4., 5.])