In [1]:
import numpy as np

In [2]:
a = [1, 2, 3, 4, 5]

In [3]:
a[-1: -3: -1]  # Output: [5, 4]

[5, 4]

In [4]:
a[: : 2]  # Output: [1, 3, 5]

[1, 3, 5]

In [5]:
arr = np.array([10, 20, 30, 40, 50])

In [6]:
arr[: : 2]  # Output: array([10, 30, 50])

array([10, 30, 50])

In [7]:
arr[-1]  # Output: 50

np.int64(50)

In [8]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [9]:
print(matrix[0:2, 1:3])  # Output: [[2 3] [5 6]]

[[2 3]
 [5 6]]


In [11]:
arr = np.array([10, 20, 30, 40, 50])
ind = [0, 2, 4]
print(np.take(arr, ind)) # Output: [10 30 50]

[10 30 50]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [13]:
for x in np.nditer(arr):
    print(x, end=' ')  # Output: 1 2 3 4 5 6 7 8 9

1 2 3 4 5 6 7 8 9 

In [14]:
for ind, x in np.ndenumerate(arr):
    print(f"Index: {ind}, Value: {x}")

Index: (0, 0), Value: 1
Index: (0, 1), Value: 2
Index: (0, 2), Value: 3
Index: (1, 0), Value: 4
Index: (1, 1), Value: 5
Index: (1, 2), Value: 6
Index: (2, 0), Value: 7
Index: (2, 1), Value: 8
Index: (2, 2), Value: 9


Views vs Copies

In [15]:
arr = np.array([1, 2, 3, 4, 5])
view = arr[1 : 3]
view

array([2, 3])

In [16]:
view[0] = 200

In [17]:
view

array([200,   3])

In [18]:
arr

array([  1, 200,   3,   4,   5])

In [19]:
copy = arr[1:3].copy()
copy

array([200,   3])

In [20]:
copy[0] = 2

In [21]:
copy

array([2, 3])

In [22]:
arr

array([  1, 200,   3,   4,   5])

In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
print(arr.transpose())  # Output: Transposed matrix

[[1 4 7]
 [2 5 8]
 [3 6 9]]
