In [6]:
import numpy as np

In [7]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)
print(reshaped)
print(reshaped.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [8]:
reshaped2 = reshaped.reshape(3, 2)
reshaped2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
ravel = reshaped2.ravel()
ravel

array([1, 2, 3, 4, 5, 6])

In [10]:
ravel[0] = 99
print(ravel)
print(reshaped2)

[99  2  3  4  5  6]
[[99  2]
 [ 3  4]
 [ 5  6]]


In [11]:
flat = reshaped2.flatten()
flat

array([99,  2,  3,  4,  5,  6])

In [12]:
flat[0] = 1
flat

array([1, 2, 3, 4, 5, 6])

In [14]:
reshaped2

array([[99,  2],
       [ 3,  4],
       [ 5,  6]])