In [1]:
import numpy as np

In [3]:
arr = np.array([[[1, 2], [3, 4]]])
arr.shape

(1, 2, 2)

In [4]:
swap = np.swapaxes(arr, 0, 2)
swap.shape

(2, 2, 1)

In [7]:
# Concatenation:

a = np.array([1, 2])
b = np.array([3, 4])

In [8]:
combine = np.concatenate((a, b))
combine

array([1, 2, 3, 4])

In [9]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

In [10]:
print(np.vstack((arr1, arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [11]:
print(np.hstack((arr1, arr2)))

[[1 2 5 6]
 [3 4 7 8]]


In [12]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

In [13]:
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [14]:
print(np.split(arr, 2))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
